apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-deployment
  labels:
    app: rev
spec:
  selector:
    matchLabels:
      app: rev-pod
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: kuber-rev-pod
      labels:
        app: rev-pod
    spec:
      containers:
        - name: nginx-rev-pod
#          args: ["123", "234"]
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
#          startupProbe:
#            httpGet:
#              port: 80
#
#            failureThreshold: 30
#            successThreshold: 1
#            periodSeconds: 5
#            initialDelaySeconds: 5
#            timeoutSeconds: 10
#          livenessProbe:
#            httpGet:
#              port: 80
#            failureThreshold: 3
#            successThreshold: 1
#            periodSeconds: 5
#            initialDelaySeconds: 5
#            timeoutSeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  selector:
    app: rev-pod
  ports:
    - port: 80
#      nodePort: 30001
      targetPort: http
      protocol: TCP
#  type: NodePort
